### ISSUE TITLE
Problem while watching? Please write comment here!

### ISSUE THREAD

**Issue by ZXArkin** [ZXArkin/my-personal-iptv#1]
Test issue

**Comment by luongz** [comment]
?

**Comment by luongz** [comment]
Thứ nhất. Lấy link của t thì lên ghi cái cre ở phần README giúp.  
Thứ hai. Không mở issue up link lên repo lớn , dễ ăn DMCA.

Thân.

**Comment by luongz** [comment]
> Thứ hai. Không mở issue up link lên repo lớn , dễ ăn DMCA.

?
